spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JacksonJsonSerializer"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
